### Query Course Request
POST {{content_host}}/content/course/list?pageNo=1&pageSize=10
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "java",
  "publishStatus": ""
}

### Query Course Category
GET {{content_host}}/content/course-category/tree-nodes?id=1
Content-Type: application/json